<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>fsl</string>
	</array>
	<key>name</key>
	<string>FSL - Finite State Language</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.mn</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>block comment</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.fsl</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>//</string>
			<key>comment</key>
			<string>block comment</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>comment.line.fsl</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\${</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>js outcalls</string>
			<key>end</key>
			<string>}</string>
			<key>name</key>
			<string>keyword.other</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>semver</string>
			<key>match</key>
			<string>([0-9]*)(\.)([0-9]*)(\.)([0-9]*)</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>fsl language directive</string>
			<key>match</key>
			<string>graph_layout(\s*)(:)</string>
			<key>name</key>
			<string>constant.language.fslLanguage.directive</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>fsl language directive</string>
			<key>match</key>
			<string>machine_name(\s*)(:)</string>
			<key>name</key>
			<string>constant.language.fslLanguage.directive</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>fsl language directive</string>
			<key>match</key>
			<string>machine_version(\s*)(:)</string>
			<key>name</key>
			<string>constant.language.fslLanguage.directive</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>fsl language directive</string>
			<key>match</key>
			<string>machine_author(\s*)(:)</string>
			<key>name</key>
			<string>constant.language.fslLanguage.directive</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>fsl language directive</string>
			<key>match</key>
			<string>machine_contributor(\s*)(:)</string>
			<key>name</key>
			<string>constant.language.fslLanguage.directive</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>fsl language directive</string>
			<key>match</key>
			<string>machine_comment(\s*)(:)</string>
			<key>name</key>
			<string>constant.language.fslLanguage.directive</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>fsl language directive</string>
			<key>match</key>
			<string>machine_definition(\s*)(:)</string>
			<key>name</key>
			<string>constant.language.fslLanguage.directive</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>fsl language directive</string>
			<key>match</key>
			<string>machine_reference(\s*)(:)</string>
			<key>name</key>
			<string>constant.language.fslLanguage.directive</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>fsl language directive</string>
			<key>match</key>
			<string>machine_license(\s*)(:)</string>
			<key>name</key>
			<string>constant.language.fslLanguage.directive</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>fsl language directive</string>
			<key>match</key>
			<string>machine_repositories(\s*)(:)</string>
			<key>name</key>
			<string>constant.language.fslLanguage.directive</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>fsl language directive</string>
			<key>match</key>
			<string>machine_language(\s*)(:)</string>
			<key>name</key>
			<string>constant.language.fslLanguage.directive</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>fsl language directive</string>
			<key>match</key>
			<string>fsl_version(\s*)(:)</string>
			<key>name</key>
			<string>constant.language.fslLanguage.directive</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>transitions</string>
			<key>match</key>
			<string>(&lt;-&gt;|↔)</string>
			<key>name</key>
			<string>keyword.control.transition.fslArrow.legal_legal</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>transitions</string>
			<key>match</key>
			<string>(&lt;-|←)</string>
			<key>name</key>
			<string>keyword.control.transition.fslArrow.legal_none</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>transitions</string>
			<key>match</key>
			<string>(-&gt;|→)</string>
			<key>name</key>
			<string>keyword.control.transition.fslArrow.none_legal</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>transitions</string>
			<key>match</key>
			<string>(&lt;=&gt;|⇔)</string>
			<key>name</key>
			<string>keyword.control.transition.fslArrow.main_main</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>transitions</string>
			<key>match</key>
			<string>(=&gt;|⇒)</string>
			<key>name</key>
			<string>keyword.control.transition.fslArrow.none_main</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>transitions</string>
			<key>match</key>
			<string>(&lt;=|⇐)</string>
			<key>name</key>
			<string>keyword.control.transition.fslArrow.main_none</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>transitions</string>
			<key>match</key>
			<string>(&lt;~&gt;|↮)</string>
			<key>name</key>
			<string>keyword.control.transition.fslArrow.forced_forced</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>transitions</string>
			<key>match</key>
			<string>(~&gt;|↛)</string>
			<key>name</key>
			<string>keyword.control.transition.fslArrow.none_forced</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>transitions</string>
			<key>match</key>
			<string>(&lt;~|↚)</string>
			<key>name</key>
			<string>keyword.control.transition.fslArrow.forced_none</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>transitions</string>
			<key>match</key>
			<string>(&lt;-=&gt;|←⇒)</string>
			<key>name</key>
			<string>keyword.control.transition.fslArrow.legal_main</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>transitions</string>
			<key>match</key>
			<string>(&lt;=-&gt;|⇐→)</string>
			<key>name</key>
			<string>keyword.control.transition.fslArrow.main_legal</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>transitions</string>
			<key>match</key>
			<string>(&lt;-~&gt;|←↛)</string>
			<key>name</key>
			<string>keyword.control.transition.fslArrow.legal_forced</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>transitions</string>
			<key>match</key>
			<string>(&lt;~-&gt;|↚→)</string>
			<key>name</key>
			<string>keyword.control.transition.fslArrow.forced_legal</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>transitions</string>
			<key>match</key>
			<string>(&lt;=~&gt;|⇐↛)</string>
			<key>name</key>
			<string>keyword.control.transition.fslArrow.main_forced</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>transitions</string>
			<key>match</key>
			<string>(&lt;~=&gt;|↚⇒)</string>
			<key>name</key>
			<string>keyword.control.transition.fslArrow.forced_main</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>action annotation</string>
			<key>match</key>
			<string>\'[^']*\'</string>
			<key>name</key>
			<string>constant.character.fslAction</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>named ordered list</string>
			<key>match</key>
			<string>\&amp;[a-zA-Z0-9_]</string>
			<key>name</key>
			<string>constant.character.namedOrderedList</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>edge probability annotation</string>
			<key>match</key>
			<string>([0-9]+)%</string>
			<key>name</key>
			<string>constant.numeric.fslProbability</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>fsl label annotation</string>
			<key>match</key>
			<string>\"[^"]*\"</string>
			<key>name</key>
			<string>entity.name.tag.fslLabel.doublequoted</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>fsl label annotation</string>
			<key>match</key>
			<string>([a-zA-Z0-9_.+&amp;()#@!?,])</string>
			<key>name</key>
			<string>entity.name.tag.fslLabel.atom</string>
		</dict>
	</array>
	<key>repository</key>
	<false/>
	<key>scopeName</key>
	<string>source.fsl</string>
	<key>uuid</key>
	<string>a4042269-e571-45d1-a332-d52b678edf75</string>
</dict>
</plist>
